blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/davidgibsonp/open-specification/discussions
    about: Ask questions or start a discussion about the Open Specification standard
